# Github Action의 이름 설정
name: Spring Boot Build Test

# Action의 Trigger 설정
on: pull_request

# 직렬 또는 병렬적으로 실행할 작업의 집합
jobs:
  # 작업의 이름
  build:
    # 작업 실행 환경 이미지 설정
    runs-on: ubuntu-latest

    # 실행할 명령들을 순서에 맞게 나열
    steps:
      # 현재 프로젝트로 작업영역 설정
      - name: Checkout
        uses: actions/checkout@v3

      # Github Action Market에 등록된 Java 환경 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      # Gradle Dependency 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 빌드 명령어 실행
      - run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
